# Generated by Django 2.2.10 on 2020-04-11 19:14

import backend.submodels.project
import backend.submodels.user
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='unamed label')),
                ('description', models.TextField(default='none description')),
                ('insertion_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='unamed dataset')),
                ('description', models.TextField(default='none description')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LossTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Optimizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimizer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(default='unamed project')),
                ('description', models.TextField(default='none description')),
                ('result', models.FloatField(default=50)),
                ('project_date', models.DateField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('progress', models.FloatField()),
                ('batch_size', models.IntegerField()),
                ('epochs', models.IntegerField()),
                ('learning_rate', models.FloatField()),
                ('weight_decay', models.FloatField()),
                ('accuracy', models.FloatField(default=0)),
                ('loss', models.FloatField(default=0)),
                ('loss_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.LossTypes')),
                ('optimizer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Optimizer')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.TextField(default='user', primary_key=True, serialize=False, unique=True)),
                ('firstname', models.TextField(default='user')),
                ('lastname', models.TextField(default='user')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1)),
                ('email', models.EmailField(default='example@email.com', max_length=254, unique=True)),
                ('occupation', models.TextField(default='undefined occupation')),
                ('image', models.TextField(blank=True, default='./static/images/default-image.jpg', null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=backend.submodels.user.nameFile)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(choices=[('t', 'Train Set'), ('d', 'Dev Set')], default='t', max_length=1)),
                ('epoch', models.IntegerField()),
                ('accuracy_rate', models.FloatField()),
                ('loss', models.FloatField()),
                ('run', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.ProjectRuns')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(default='unknown role')),
                ('presmissions', models.IntegerField(default=1)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Project')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.AddField(
            model_name='projectruns',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='unamed')),
                ('type', models.TextField(default='untyped')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=backend.submodels.project.nameFile)),
                ('insertion_date', models.DateField(auto_now_add=True)),
                ('main', models.BooleanField(default=False)),
                ('insert_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.CreateModel(
            name='LabelsMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('label', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='label', to='backend.DataLabel')),
                ('prediction', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='backend.DataLabel')),
                ('run', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.ProjectRuns')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetCollectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(default='unknown role')),
                ('presmissions', models.IntegerField(default=1)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('dataset', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Dataset')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.AddField(
            model_name='datalabel',
            name='dataset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Dataset'),
        ),
        migrations.AddField(
            model_name='datalabel',
            name='insert_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(default='item')),
                ('insert_date', models.DateField(auto_now_add=True)),
                ('dataset', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Dataset')),
                ('insert_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
                ('label', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.DataLabel')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField(default='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
    ]
