# Generated by Django 2.2.10 on 2020-04-25 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='model_type',
            field=models.CharField(choices=[('u', 'User Upload'), ('c', 'Customizable'), ('k', 'Known Model')], default='u', max_length=1),
        ),
        migrations.CreateModel(
            name='ProjectKnownModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.KnownModels')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Project')),
            ],
        ),
    ]
