# Generated by Django 2.2.10 on 2020-05-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200425_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='best_run_saved',
            field=models.FloatField(default=0),
        ),
    ]
