# Generated by Django 2.2.10 on 2020-05-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_project_best_run_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='best_run_saved',
            new_name='best_model_saved',
        ),
        migrations.AlterField(
            model_name='project',
            name='result',
            field=models.FloatField(default=0),
        ),
    ]
