# Generated by Django 2.2.10 on 2020-05-27 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200520_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='public_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='public_view',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DatasetFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Dataset')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
    ]
