# Generated by Django 3.0.5 on 2020-05-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNotifcation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Project')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.CreateModel(
            name='DatesetNotifcation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('dataset', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Dataset')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
    ]
