# Generated by Django 3.0.5 on 2020-05-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_datesetnotifcation_projectnotifcation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(blank=True, default='')),
                ('complete', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('executor_task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Project')),
            ],
        ),
    ]
