# Generated by Django 2.2.10 on 2020-05-28 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200528_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlabeledSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(default='item')),
                ('insert_date', models.DateField(auto_now_add=True)),
                ('dataset', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Dataset')),
                ('insert_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
    ]
