# Generated by Django 2.2.10 on 2020-05-29 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_unlabeledsamples'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownmodels',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
