# Generated by Django 2.2.10 on 2020-06-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_knownmodels_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownmodels',
            name='image',
            field=models.TextField(default='/static/images/alexnet.jpg'),
            preserve_default=False,
        ),
    ]
