# Generated by Django 3.0.5 on 2020-08-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_projectchecklist'),
        ('backend', '0009_knownmodels_image'),
    ]

    operations = [
    ]
