# Generated by Django 2.2.10 on 2020-08-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_knownmodels_image'),
        ('backend', '0007_projectchecklist'),
    ]

    operations = [
    ]
