# Generated by Django 2.2.10 on 2020-08-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200804_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postgroups',
            old_name='Post',
            new_name='post',
        ),
    ]
