# Generated by Django 2.2.10 on 2020-08-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200805_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postfollowed',
            old_name='Post',
            new_name='post',
        ),
    ]
