# Generated by Django 2.2.10 on 2020-08-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20200808_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dev_percentage',
            field=models.IntegerField(default=0.2),
        ),
        migrations.AddField(
            model_name='project',
            name='height',
            field=models.IntegerField(default=64),
        ),
        migrations.AddField(
            model_name='project',
            name='test_percentage',
            field=models.IntegerField(default=0.1),
        ),
        migrations.AddField(
            model_name='project',
            name='train_percentage',
            field=models.IntegerField(default=0.7),
        ),
        migrations.AddField(
            model_name='project',
            name='width',
            field=models.IntegerField(default=64),
        ),
    ]
