# Generated by Django 2.2.10 on 2020-08-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20200809_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dev_percentage',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='test_percentage',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='train_percentage',
            field=models.IntegerField(default=70),
        ),
    ]
