# Generated by Django 3.0.5 on 2020-08-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_merge_20200803_2257'),
        ('backend', '0016_auto_20200809_2036'),
    ]

    operations = [
    ]
