# Generated by Django 2.2.10 on 2020-08-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20200809_2337'),
        ('backend', '0017_merge_20200809_2341'),
    ]

    operations = [
    ]
