/* file to hold the states/types */

/* Login actions */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT'

/* User actions */
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_PROJECTS = 'GET_USER_PROJECTS';
export const USER_LOOKUP_SUCCESS = 'USER_LOOKUP_SUCCESS';
export const USER_LOOKUP_FAIL = 'USER_LOOKUP_FAIL';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_IMAGE = 'UPDATE_USER_IMAGE';

/* Project actions */
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const SELECT_PROJECT = 'SELECT_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const GET_PROJECT_TEAM = 'GET_PROJECT_TEAM';
export const DELETE_MEMBER_TEAM = 'DELETE_MEMBER_TEAM';
export const ADD_MEMBER_TEAM = 'ADD_MEMBER_TEAM';
export const UPLOAD_MODEL_FILES = 'UPLOAD_MODEL_FILES';
export const GET_PROJECT_FILES = 'GET_PROJECT_FILES';
export const SELECT_FILE = 'SELECT_FILE';
export const GET_FILE_CONTENT = 'GET_FILE_CONTENT';
export const UPDATE_FILE_CONTENT = 'UPDATE_FILE_CONTENT';
export const RUN_MODEL = 'RUN_MODEL';
export const ADD_RUN_RECORD = 'ADD_RUN_RECORD';
export const GET_UNFINISHED_RUNS = 'GET_UNFINISHED_RUNS';
export const GET_LOSS_TYPES = 'GET_LOSS_TYPES';
export const GET_OPTIMIZER_TYPES = 'GET_OPTIMIZER_TYPES';
export const GET_PROJECT_RUNS = 'GET_PROJECT_RUNS';
export const GET_RUN_RESULT_TRAIN = 'GET_RUN_RESULT_TRAIN';
export const GET_RUN_RESULT_DEV = 'GET_RUN_RESULT_DEV';
export const SELECT_RUN = 'SELECT_RUN';
export const CLEAR_RUN = 'CLEAR_RUN';
export const GET_RECALL_RESULT = 'GET_RECALL_RESULT';
export const GET_PRECISION_RESULT = 'GET_PRECISION_RESULT';
export const GET_F1_RESULT = 'GET_F1_RESULT';
export const GET_CONFUSION_MATRIX = 'GET_CONFUSION_MATRIX';

/* Project Sections Status */
export const PROJECT_DETAILS_ACTIVE = 'PROJECT_DETAILS_ACTIVE';
export const PROJECT_DETAILS_NONACTIVE = 'PROJECT_DETAILS_NONACTIVE';
export const PROJECT_TEAM_ACTIVE = 'PROJECT_TEAM_ACTIVE';
export const PROJECT_TEAM_NONACTIVE = 'PROJECT_TEAM_NONACTIVE';
export const MODEL_FILES_ACTIVE = 'MODEL_FILES_ACTIVE';
export const MODEL_FILES_NONACTIVE = 'MODEL_FILES_NONACTIVE';
export const PROJECT_NOTIFICATIONS_ACTIVE = 'PROJECT_NOTIFICATIONS_ACTIVE';
export const PROJECT_NOTIFICATIONS_NONACTIVE = 'PROJECT_NOTIFICATIONS_NONACTIVE';
export const RUNS_OUTCOMES_ACTIVE = 'RUNS_OUTCOMES_ACTIVE';
export const RUNS_OUTCOMES_NONACTIVE = 'RUNS_OUTCOMES_NONACTIVE';
export const PROJECT_RECOMMENDATIONS_ACTIVE = 'PROJECT_RECOMMENDATIONS_ACTIVE';
export const PROJECT_RECOMMENDATIONS_NONACTIVE = 'PROJECT_RECOMMENDATIONS_NONACTIVE';
export const PROJECT_TESTS_ACTIVE = 'PROJECT_TESTS_ACTIVE';
export const PROJECT_TESTS_NONACTIVE = 'PROJECT_TESTS_NONACTIVE';
export const PROJECT_STACTICS_ACTIVE = 'PROJECT_STACTICS_ACTIVE';
export const PROJECT_STACTICS_NONACTIVE = 'PROJECT_STACTICS_NONACTIVE';
export const PROJECT_DIAGRAMS_ACTIVE = 'PROJECT_DIAGRAMS_ACTIVE';
export const PROJECT_DIAGRAMS_NONACTIVE = 'PROJECT_DIAGRAMS_NONACTIVE';
export const MODEL_INTERACTION_ACTIVE = 'MODEL_INTERACTION_ACTIVE';
export const MODEL_INTERACTION_NONACTIVE = 'MODEL_INTERACTION_NONACTIVE';
export const RUN_MODEL_ACTIVE = 'RUN_MODEL_ACTIVE';
export const RUN_MODEL_NONACTIVE = 'RUN_MODEL_NONACTIVE';
export const ACCESS_DATASET_ACTIVE = 'ACCESS_DATASET_ACTIVE';
export const ACCESS_DATASET_NONACTIVE = 'ACCESS_DATASET_NONACTIVE';
export const EMBED_APPLICATION_ACTIVE = 'EMBED_APPLICATION_ACTIVE';
export const EMBED_APPLICATION_NONACTIVE = 'EMBED_APPLICATION_NONACTIVE';
export const CHECK_LIST_ACTIVE = 'CHECK_LIST_ACTIVE';
export const CHECK_LIST_NONACTIVE = 'CHECK_LIST_NONACTIVE';

/* Datasets actions */
export const GET_USER_DATASETS = 'GET_USER_DATASETS';
export const CREATE_DATASET = 'CREATE_DATASET';
export const DELETE_DATASET = 'DELETE_DATASET';
export const UPDATE_DATASET = 'UPDATE_DATASET';
export const GET_DATASETS_ITEMS_AMOUNT = 'GET_DATASETS_ITEMS_AMOUNT';
export const GET_DATASET_ITEMS = 'GET_DATASET_ITEMS';
export const GET_DATASET_TEAM = 'GET_DATASET_ITEMS';
export const SELECT_DATASET = 'SELECT_DATASET';
export const GET_DATASET_LABELS = 'GET_DATASET_LABELS';
export const GET_LABELS_COUNT = 'GET_LABELS_COUNT';
export const GET_ITEMS_COUNT = 'GET_ITEMS_COUNT';
export const GET_DATA_ITEMS = 'GET_DATA_ITEMS';
export const SELECT_DATA_ITEM = 'SELECT_DATA_ITEM';
export const DELETE_DATA_ITEM = 'DELETE_DATA_ITEM';
export const ADD_LABEL = 'ADD_LABEL';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_LABEL = 'DELETE_LABEL';


/* Datasets toggle actions */
export const DATASET_DETAILS_ACTIVE = 'DATASET_DETAILS_ACTIVE';
export const DATASET_DETAILS_NONACTIVE = 'DATASET_DETAILS_NONACTIVE';
export const COLLECTORS_TEAM_ACTIVE = 'COLLECTORS_TEAM_ACTIVE';
export const COLLECTORS_TEAM_NONACTIVE = 'COLLECTORS_TEAM_NONACTIVE';
export const LABELS_SECTION_ACTIVE = 'LABELS_SECTION_ACTIVE';
export const LABELS_SECTION_NONACTIVE = 'LABELS_SECTION_NONACTIVE';
export const ITEMS_SECTION_ACTIVE = 'ITEMS_SECTION_ACTIVE';
export const ITEMS_SECTION_NONACTIVE = 'ITEMS_SECTION_NONACTIVE';
export const ADD_LABEL_ACTIVE = 'ADD_LABEL_ACTIVE';
export const ADD_LABEL_NONACTIVE = 'ADD_LABEL_NONACTIVE';
export const ADD_ITEM_ACTIVE = 'ADD_ITEM_ACTIVE';
export const ADD_ITEM_NONACTIVE = 'ADD_ITEM_NONACTIVE';

/* Profile toggle actions */
export const CHANGE_PASSWORD_ACTIVE = 'CHANGE_PASSWORD_ACTIVE';
export const CHANGE_PASSWORD_NONACTIVE = 'CHANGE_PASSWORD_NONACTIVE';
export const PERSONAL_DETAILS_ACTIVE = 'PERSONAL_DETAILS_ACTIVE';
export const PERSONAL_DETAILS_NONACTIVE = 'PERSONAL_DETAILS_NONACTIVE';
export const ACTIVENESS_SECTION_ACTIVE = 'ACTIVENESS_SECTION_ACTIVE';
export const ACTIVENESS_SECTION_NONACTIVE = 'ACTIVENESS_SECTION_NONACTIVE';
export const CHANGE_IMAGE_ACTIVE = 'CHANGE_IMAGE_ACTIVE';
export const CHANGE_IMAGE_NONACTIVE = 'CHANGE_IMAGE_NONACTIVE';

/* Automated Model Builder */
export const SELECT_LAYER = 'SELECT_LAYER';
export const UPDATE_LAYER = 'UPDATE_LAYER';
export const UPDATE_MODEL_DETAILS = 'UPDATE_MODEL_DETAILS';
export const ADD_LAYER = 'ADD_LAYER';
